                                   01 -03 The Power of Numpy

Pandas is a wrapper for Numpy

                   You can consider the values of the dataframe as a ndarray from numpy.
 
 
 
 To extract those values, we set:
 
 nd1 = df1.values

In [1]:
#                nd1 = df1.values

2 - Acess data within a nd array

In [3]:
#   nd1[row, column]
#   nd[0] is the first element (zero indexed)
#   nd1[-1] -- last row


                                      Remember to review numpy syntax and notation!

In [20]:
import numpy as np

In [13]:
nd1 = np.array([(2,3,4), (5,6,7)]) #this function can take tuples, lists, etc
# each parentesis will output one row

In [14]:
print (nd1) #this output is an array

[[2 3 4]
 [5 6 7]]


                                       We shall now create an empty array

In [15]:
nd2 = np.empty(5)

In [16]:
print (nd2) #the default data type is float

[  4.19957958e-316   2.56053078e-316   4.74569420e-317   8.97222399e-315
   2.22260877e-313]


In [19]:
nd2 = np.empty((5, 4, 3))

In [20]:
print (nd2)

[[[  3.39953912e-308   0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   3.44286782e-300   0.00000000e+000]
  [  0.00000000e+000   0.00000000e+000   1.54223259e-308]
  [  9.34157964e-315   2.96439388e-323   4.72044745e-316]]

 [[  1.64088351e-303   0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   3.51146612e+151   1.29744654e-311]
  [  1.62969277e-311   3.63964718e-310   2.49208273e-306]
  [ -3.13264791e-294   1.63321263e-301   1.33442067e+241]]

 [[  4.74783839e-309   2.15208490e-282   5.72972541e+250]
  [  1.03105230e-308   1.45261014e-296   7.23386757e+221]
  [  2.06427796e-309   9.51986434e-292   3.92052692e+202]
  [  2.51744294e-292   1.30918653e-308   2.87522673e-188]]

 [[  1.07042855e-296   1.27749738e+294   1.17555177e-308]
  [  2.49208610e-306   3.91957011e+202   1.30972982e-308]
  [  2.49210917e-306   3.91957011e+202   9.00293893e-066]
  [  1.44879697e-308   6.05841488e-268   5.17883716e+120]]

 [[  5.74659350e+250   1.44879689e-308   3.61530488e+223]
  [  3

                                      Creating an array of ones

In [21]:
nd2=np.ones((5,4))

In [22]:
print(nd2)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


                                    Changing the data type

In [26]:
nd2 = np.ones((5,4), dtype=np.int)

In [27]:
print (nd2
      )

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [1]:
#you can create an array full of zeros with np.zeros()

                                        Generate random values

In [23]:
#we call the random method -- from [0.0,1.0)
print (np.random.random((5,4)))
    

[[ 0.68449049  0.39252876  0.93416813  0.74532811]
 [ 0.05199344  0.99588688  0.02060116  0.09253283]
 [ 0.52918278  0.28176663  0.20647013  0.08881505]
 [ 0.75941203  0.46187804  0.66786053  0.40801456]
 [ 0.00807548  0.56772481  0.51704294  0.04321833]]


In [22]:
#another way
print (np.random.rand(5,4))

[[ 0.88882085  0.06176877  0.49620764  0.9632905 ]
 [ 0.19259994  0.25525041  0.09451388  0.65657066]
 [ 0.77836734  0.73455773  0.66014369  0.44314557]
 [ 0.83452824  0.21786352  0.80009147  0.97182481]
 [ 0.12135228  0.25669378  0.55756154  0.47096292]]


In [24]:
#random with normal distribution -- default: mean=0 ; standart deviation=1.0
print (np.random.normal(size=(2,3)))

[[ 0.32260683  0.07597822 -2.04894501]
 [ 1.37339213  0.58317044 -1.13438725]]


In [26]:
# we can change the mean and standart deviation
# in the example, we use mean =5, std.dev =0.2
print (np.random.normal(5,0.2, size=(2,3)))

[[ 5.07236987  4.93885009  5.06998003]
 [ 5.1016521   5.25338694  5.10606565]]


In [29]:
#we can also print random integers calling the randint() function
print (np.random.randint(10)) #a single integer in [0,10)
print (np.random.randint(0,10)) #explict high and low
print (np.random.randint(0,10, size=5) )# 1D array of 5 random integers
print (np.random.randint(0, 10, size=(2,3))) #2x3 array of random integers


4
4
[5 4 7 5 6]
[[8 9 7]
 [5 3 9]]


                                              Array attributes

In [35]:
# create a new array
nd3 = np.ones((5,4))
#print the shape using the shape attribute
print (nd3.shape)
# print the number of rows
print (nd3.shape[0])
# print nmber of columns
print (nd3.shape[1])

(5, 4)
5
4


In [36]:
# finding the dimension of the array using the len() function
print (len(nd3.shape))

2


In [37]:
# retrieve the number of elements using the size attribute
print (nd3.size)

20


In [38]:
# find the type of data using the dtype attribute
# float64 stands for 64-bit float numbers
print (nd3.dtype)

float64


                                          Operations on ndarrays

In [41]:
# we use the seed number generator to get the same numbers every time
np.random.seed(693)
a=np.random.randint(0,10,size=(5,4))
print ("Array: \n", a)

Array: 
 [[2 0 5 1]
 [1 3 4 4]
 [9 2 9 1]
 [9 3 7 5]
 [4 7 0 3]]


In [43]:
# call the .sum() function to get the sum of the elemenst of the array
print (a.sum())

79


In [44]:
# iterate over rows, to compute sum of each column
print("Sum of each column: \n", a.sum(axis=0))

Sum of each column: 
 [25 15 25 14]


In [45]:
# iterate over columns, to compute the sum of each row
print ("Sum of each row: \n", a.sum(axis=1))

Sum of each row: 
 [ 8 12 21 24 14]


In [46]:
#Statistics 


In [47]:
#min
print ("Minimum of each column: \n", a.min(axis=0))

Minimum of each column: 
 [1 0 0 1]


In [49]:
#max
print ("Maximum of each row: \n", a.max(axis=1))

Maximum of each row: 
 [5 4 9 9 7]


In [52]:
#mean 
print ("Mean of all elements: \n", a.mean())

Mean of all elements: 
 3.95


In [53]:
# finding the index of the maximum value
print (np.argmax(a))


8


                                          Timing python operations

In [54]:
import time

In [56]:
# calculate how long the operation takes by subtracting two time snapshots
t1 = time.time()
print ("The Awaken One")
t2=time.time()
print("The total time taken by the print statement is  ", t1-t2, "seconds")

The Awaken One
The total time taken by the print statement is   -0.0010001659393310547 seconds


In [60]:
# Numpy is faster than the other methods

b = np.random.random((1000,1000))

def manual_mean(arr):
    sum=0
    for i in xrange(0,arr.shape[0]):
        for j in xrange(0,arr.shape[1]):
            sum=sum+arr[i,j]
    return sum/arr.size

def numpy_mean(arr):
    return arr.mean()

def how_long(fnc, *args):
    t0=time()
    result=func(*args)
    t1=time()
    return result , t1-t0



                                          Acessing array elements

In [63]:
# acessing an element
#the row and column index starts from zero
element =a[3,2]
print (element)

7


In [68]:
# slicing operation
# first we pass 0 or 1 (row or column), then we pass the desired output
print (a[0, 1:3])

[0 5]


In [69]:
# getting a subset of the array
print(a[0:2, 0:2])

[[2 0]
 [1 3]]


In [71]:
# note
# slicing n:m:t specifies a range that starts at n, stops before m, in steps of size t.
# the next statement will select columns 0 and 2 for every row
print (a[:, 0:3:2])

[[2 5]
 [1 4]
 [9 9]
 [9 7]
 [4 0]]


                                            Modifying array elements

In [73]:
a[0,0]=2
print (a)

[[2 0 5 1]
 [1 3 4 4]
 [9 2 9 1]
 [9 3 7 5]
 [4 7 0 3]]


In [76]:
# modifying a whole row
a[0, : ]=2
print (a)

[[2 2 2 2]
 [1 3 4 4]
 [9 2 9 1]
 [9 3 7 5]
 [4 7 0 3]]


In [77]:
# you can assign a list of values to a row or a column
a[:, 3] = [22,23,24,25,26]
print (a)

[[ 2  2  2 22]
 [ 1  3  4 23]
 [ 9  2  9 24]
 [ 9  3  7 25]
 [ 4  7  0 26]]


                                      Indexing arrays with other arrays

In [79]:
#creating an one dimensional array of 5 elements
c=np.random.random(5)
# creating a list of indices
indices = np.array([1,1,2,3])
print (a[indices])



[[ 1  3  4 23]
 [ 1  3  4 23]
 [ 9  2  9 24]
 [ 9  3  7 25]]


In [82]:
# boolean index arrays
mean = a.mean()
print (mean)
print (a[a<mean])

9.2
[2 2 2 1 3 4 9 2 9 9 3 7 4 7 0]


In [84]:
a[a<mean]=mean
print (a)

[[ 9  9  9 22]
 [ 9  9  9 23]
 [ 9  9  9 24]
 [ 9  9  9 25]
 [ 9  9  9 26]]


In [85]:
d=a*2
print (d)

[[18 18 18 44]
 [18 18 18 46]
 [18 18 18 48]
 [18 18 18 50]
 [18 18 18 52]]


In [90]:
d=a/2
print(d)

[[  4.5   4.5   4.5  11. ]
 [  4.5   4.5   4.5  11.5]
 [  4.5   4.5   4.5  12. ]
 [  4.5   4.5   4.5  12.5]
 [  4.5   4.5   4.5  13. ]]


In [91]:
# in NumPy, the product of two array won't give yo the matrix product. It will give you element-wise multiplication
print (a*d)

[[  40.5   40.5   40.5  242. ]
 [  40.5   40.5   40.5  264.5]
 [  40.5   40.5   40.5  288. ]
 [  40.5   40.5   40.5  312.5]
 [  40.5   40.5   40.5  338. ]]
